services:
  compliance:
    build:
      context: .
      # Choose the Dockerfile directly based on BUILD_TYPE
      dockerfile: ${DOCKERFILE:-Dockerfile}
      args:
        # Pass the build type for internal use
        - BUILD_TYPE=${BUILD_TYPE:-full}
        - EXTRA_CERT=${EXTRA_CERT:-false}
    container_name: compliance-as-code
    volumes:
      - ./output:/output
      # Mount extra certificate if available - the variable will be empty if not provided
      - ${EXTRA_CERT_PATH:+./certs/org/extra-ca-bundle.pem}:/extra-ca-bundle.pem:ro
    tty: true
    command: >
      -c "source /etc/profile.d/welcome.sh &&
          tail -f /dev/null"

