baseURL = 'https://mitre.github.io/cac-builder/'
languageCode = 'en-us'
title = 'ComplianceAsCode Builder'
theme = 'docsy'

# Language settings
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false

# Docsy theme settings
[params]
  copyright = "The MITRE Corporation"
  github_repo = "https://github.com/mitre/cac-builder"
  github_branch = "main"
  
  # Versioning
  version_menu = "Releases"
  archived_version = false
  version = "latest"
  
  # Navigation
  [params.ui]
    sidebar_menu_compact = true
    sidebar_menu_foldable = true
    sidebar_cache_limit = 10
    sidebar_search_disable = false
    navbar_logo = true
    
  # Footer links
  [[params.links.user]]
    name = "GitHub"
    url = "https://github.com/mitre/cac-builder"
    icon = "fab fa-github"
    desc = "Development takes place here!"
    
  # Top-level sections
  [[menu.main]]
    name = "Documentation"
    weight = 10
    url = "/docs/"
    
  [[menu.main]]
    name = "Getting Started"
    weight = 20
    url = "/getting-started/"
    
  [[menu.main]]
    name = "Development"
    weight = 30
    url = "/development/"
    
  [[menu.main]]
    name = "GitHub"
    weight = 40
    url = "https://github.com/mitre/cac-builder"
