name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Set permissions explicitly for security best practices
permissions:
  contents: read  # For checking out code
  packages: read  # For pulling container images
  # Note: For PR builds, we don't need write permissions

jobs:
  build:
    name: Build and Test Containers
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Create certificate file for build
        run: |
          mkdir -p certs/org
          
          # Function to create certificate from parts
          create_cert_from_parts() {
            # Start with an empty file
            : > certs/org/ca-bundle.pem
            
            # Add each available part (up to 20 parts)
            for i in {1..20}; do
              SECRET_NAME="CA_BUNDLE_PART$i"
              if [ -n "$(eval echo \${{ secrets.$SECRET_NAME }})" ]; then
                echo "Adding certificate part $i"
                echo "$(eval echo \${{ secrets.$SECRET_NAME }})" >> certs/org/ca-bundle.pem
              else
                # Stop when we run out of parts
                break
              fi
            done
            
            echo "Using CA certificate assembled from multiple parts"
          }
          
          # First try using single secret
          if [ -n "${{ secrets.CA_BUNDLE }}" ]; then
            echo "${{ secrets.CA_BUNDLE }}" > certs/org/ca-bundle.pem
            echo "Using CA certificate from single secret"
          # Next try using split certificate parts
          elif [ -n "${{ secrets.CA_BUNDLE_PART1 }}" ]; then
            create_cert_from_parts
          else
            # Fallback to empty file
            touch certs/org/empty-ca-bundle.pem
            echo "Using empty CA certificate file"

      - name: Prepare Dockerfiles
        run: |
          # Instead of relying on symlinks, directly reference the actual files
          echo "Using Dockerfile for full build"
          echo "Using Dockerfile.optimized for minimal build"
      
      - name: Build minimal container
        uses: docker/build-push-action@v4
        with:
          context: .
          # Directly use the actual Dockerfile.optimized instead of a symlink
          file: ./Dockerfile.optimized
          push: false
          tags: cac-builder:minimal-test
          cache-from: type=gha
          cache-to: type=gha,mode=max
          load: true
      
      - name: Test minimal container
        run: |
          docker run --rm cac-builder:minimal-test -c "mkdir -p /content/build && cd /content/build && cmake .. && echo 'Build environment test: SUCCESS'"
      
      - name: Build full container
        uses: docker/build-push-action@v4
        with:
          context: .
          # Directly use the actual Dockerfile instead of a symlink
          file: ./Dockerfile
          push: false
          tags: cac-builder:full-test
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BUILD_TYPE=full
          load: true
      
      - name: Test full container
        run: |
          mkdir -p output
          docker run -v ${{ github.workspace }}/output:/output --rm cac-builder:full-test -c "ls /content/build/ssg-* && cp /content/build/ssg-rhel* /output/ 2>/dev/null || echo 'No content found, checking build environment'"
          
      - name: Verify output files (full build only)
        run: |
          ls -la output/ || echo "No output files found - this is expected in PR builds"
